services:
    '@enhavo/media-library/manager/MediaLibraryManager':
        chunk: 'media-library'
        import: MediaLibraryManager
        arguments:
            - '@enhavo/app/frame/FrameEventDispatcher'
            - '@enhavo/app/frame/FrameManager'
            - '@enhavo/app/flash-message/FlashMessenger'
            - '@enhavo/app/routing/Router'
            - '@enhavo/app/translation/Translator'
            - '@enhavo/app/action/ActionManager'
            - '@enhavo/app/filter/FilterManager'
            - '@enhavo/app/column/ColumnManager'
            - '@enhavo/app/batch/BatchManager'
            - '@enhavo/app/collection/CollectionFactory'
        tags:
            - { name: vue.service, service: 'mediaLibraryManager', reactive: true }

    '@enhavo/media-library/loader/MediaLibraryLoader':
        chunk: 'form'
        arguments:
            - '@enhavo/app/frame/FrameEventDispatcher'
            - '@enhavo/app/frame/FrameManager'
            - '@enhavo/core/Router'
        tags:
            - 'enhavo_app.form'

    '@enhavo/media-library/action/MediaLibraryUploadAction':
        import: MediaLibraryUploadAction
        chunk: 'action'
        tags:
            - 'enhavo_app.action'

    '@enhavo/media-library/collection/MediaLibraryCollection':
        import: MediaLibraryCollection
        chunk: 'collection'
        arguments:
            - '@enhavo/app/routing/Router'
            - '@enhavo/app/filter/FilterManager'
            - '@enhavo/app/column/ColumnManager'
            - '@enhavo/app/frame/FrameManager'
        tags:
            - { name: enhavo_app.collection }
